version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "studs"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    networks:
      - web-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  openam:
    image: "openidentityplatform/openam:latest"
    hostname: "openam.example.org"
    container_name: openam
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - openam-data:/usr/openam/config
    networks:
      - web-network

  spring:
    build:
      context: .
      dockerfile: Dockerfile-dragonusiki
    ports:
      - "8081:8081"
    networks:
      - web-network
    depends_on:
      - postgres
      - openam

  front:
    image: frontik:latest
    hostname: "openam.example.org"
    networks:
      - web-network
    ports:
      - "8083:80"
    depends_on:
      - spring

  minio:
    image: minio/minio:latest
    container_name: "miniooooooo"
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-storage:/data
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  openam-data: { }
  postgres-data: { }
  minio-storage: {}